### ISSUE TITLE
TypeError: Cannot read property 'run' of undefined

### ISSUE THREAD

**Issue by huleiEthan** [ktsn/vue-auto-routing#5]
``` shell
TypeError: Cannot read property 'run' of undefined
    at VueAutoRoutingPlugin.apply (C:\code\base-component\packages\mo-ui\examples\mo-ui-example\node_modules\vue-auto-routing\lib\webpack-plugin.js:22:24)
    at Compiler.apply (C:\code\base-component\packages\mo-ui\examples\mo-ui-example\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (C:\code\base-component\packages\mo-ui\examples\mo-ui-example\node_modules\webpack\lib\webpack.js:33:19)
```
![image](https://user-images.githubusercontent.com/9008089/53232693-999ae300-36c6-11e9-8840-b6d7d1909112.png)

package.json
```json
  "dependencies": {
    "@wps/mo-ui": "^0.2.2-alpha.0",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^8.2.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-jest": "^21.0.2",
    "babel-loader": "^7.1.1",
    "babel-plugin-component": "^1.1.1",
    "babel-plugin-dynamic-import-node": "^1.2.0",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^2.0.1",
    "chromedriver": "^2.27.2",
    "copy-webpack-plugin": "^4.0.1",
    "cross-spawn": "^5.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^4.15.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "nightwatch": "^0.9.12",
    "node-notifier": "^5.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "selenium-server": "^3.0.1",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-auto-routing": "^0.3.0",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  },
```

**Comment by ktsn** [comment]
Please try to use webpack >= 4.

**Comment by ktsn** [comment]
Closing as this is probably because of webpack version. I've just stated the supported webpack version in the docs. https://github.com/ktsn/vue-auto-routing#requirements
